### ISSUE TITLE
חסר מדריך

### ISSUE THREAD

**Issue by erelsgl** [AD-DG-games/DoubleMath3D#1]
הגרפיקה יפה, אבל אין שום מדריך שמסביר מה צריך לעשות.
גם, כשנופלים למטה מגיעים לעולם יפה ומעניין, אבל לא ברור איך לחזור למשחק המקורי.
והשעון לא מתחיל לעבוד.

**Comment by dvirGev** [comment]
תיקנו את הכל, תודה רבה :)
