### ISSUE TITLE
למה המצלמה זזה כל הזמן?

### ISSUE THREAD

**Issue by erelsgl** [AD-DG-games/DoubleMath3D#2]
א. שיחקתי בגירסה החדשה,  במשחק לשחקן יחיד, והמצלמה כל הזמן זזה - מתרחקת, מתקרבת, מסתובבת וכו'. אני לא מצליח לראות איפה אני.

ב. הזמן לא מתחיל לרוץ.

ג. כל הריבועים אותו הדבר - 5+5.

**Comment by erelsgl** [comment]
ד. ובגירסה המרובת-שחקנים, המצלמה מסתובבת בכיוון ההפוך לכיוון תנועת העכבר.

**Comment by erelsgl** [comment]
ה. המצלמה ממוקמת בזוית מאד לא נוחה.

**Comment by erelsgl** [comment]
אחרי שמנצחים, צריך לקרות משהו - אולי לחזור למסך הפתיחה.

**Comment by dvirGev** [comment]
טיפלנו בהכל, אפילו הוספנו מצב signal player מיוחד :)

**Comment by erelsgl** [comment]
עכשיו עובד הרבה יותר טוב.

א. אני עדיין חושב שמיקום המצלמה בעייתי. האם ניסיתם לשים את המצלמה על השחקן ("משחק גוף ראשון")? אפשר גם לשים את המצלמה למעלה, מה שנקרא "נקודת מבט איזומטרית", כך שהיא תקלוט גם את הלוח וגם את המסך.

ב.  האם אפשר לסמן לשחקן בצורה כלשהי מהי הדמות שלו? או לפחות לעשות דמויות בצבעים שונים, כך שהשחקן יוכל לזהות את עצמו.
