### ISSUE TITLE
לא ברור מתי מתחיל המשחק

### ISSUE THREAD

**Issue by VictoKu1** [AD-DG-games/DoubleMath3D#3]
מעבר לאנימציה ההתחלתית לא ברור מתי מתחיל המשחק.

**Comment by afikdamri** [comment]
טופל, תודה רבה (:

**Comment by dvirGev** [comment]
המשחק מתחיל ברגע שיש שני שחקנים, או כשבוחרים אפשרות ל signal player

**Comment by VictoKu1** [comment]
קשה לראות את שאר הקוביות צריך ממש להלחם עם העכבר כדי לשנות את הזוית של המצלמה.

**Comment by VictoKu1** [comment]
כדאי להוסיף את האפשרות שהטימר יפסיק לעבוד כשמגיעים לתשובה הנכונה, או כשקופצים כמה פעמים בנקודה שאותה בחרו כדי לא לחכות 30 שניות כל פעם.

**Comment by VictoKu1** [comment]
במשחק של 2 שחקנים, רואים אחד את השני כאלו השני בקפיצה.

**Comment by VictoKu1** [comment]
כשנגמר המשחק, אחרי המוזיקה יש אודיו עם שם של אתר כלשהו (אלא אם כן אתם מפרסמים שם משהו).
